export const preferences = {
  'idPkg:Preferences': {
    DocumentPreference: {
      Properties: {
        ColumnGuideColor: { '#text': 'Violet', type: 'enumeration' },
        MarginGuideColor: { '#text': 'Magenta', type: 'enumeration' },
      },
      PageHeight: '155.90551181102364',
      PageWidth: '510.23622047244095',
      CreatePrimaryTextFrame: 'false',
      PagesPerDocument: '1',
      FacingPages: 'false',
      DocumentBleedTopOffset: '8.503937007874017',
      DocumentBleedBottomOffset: '8.503937007874017',
      DocumentBleedInsideOrLeftOffset: '8.503937007874017',
      DocumentBleedOutsideOrRightOffset: '8.503937007874017',
      DocumentBleedUniformSize: 'true',
      SlugTopOffset: '0',
      SlugBottomOffset: '0',
      SlugInsideOrLeftOffset: '0',
      SlugRightOrOutsideOffset: '0',
      DocumentSlugUniformSize: 'false',
      PreserveLayoutWhenShuffling: 'true',
      AllowPageShuffle: 'true',
      OverprintBlack: 'true',
      ColumnGuideLocked: 'true',
      Intent: 'PrintIntent',
      PageBinding: 'LeftToRight',
      ColumnDirection: 'Horizontal',
      MasterTextFrame: 'false',
      SnippetImportUsesOriginalLocation: 'false',
    },
    MarginPreference: {
      ColumnCount: '1',
      ColumnGutter: '12',
      Top: '36',
      Bottom: '36',
      Left: '36',
      Right: '36',
      ColumnDirection: 'Horizontal',
    },
    ViewPreference: {
      PointsPerInch: '72',
      HorizontalCustomPoints: '12',
      VerticalCustomPoints: '12',
      StrokeMeasurementUnits: 'Points',
      GuideSnaptoZone: '4',
      CursorKeyIncrement: '0.70866141732283',
      HorizontalMeasurementUnits: 'Millimeters',
      VerticalMeasurementUnits: 'Millimeters',
      RulerOrigin: 'SpreadOrigin',
      ShowRulers: 'true',
      ShowFrameEdges: 'true',
      LineMeasurementUnits: 'Points',
      TypographicMeasurementUnits: 'Points',
      TextSizeMeasurementUnits: 'Points',
      PrintDialogMeasurementUnits: 'Millimeters',
      ShowNotes: 'true',
    },
  },
};
