// eslint-disable-next-line eslint-comments/disable-enable-pair
/* eslint-disable no-irregular-whitespace */

export const FontsMockData = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<idPkg:Fonts xmlns:idPkg="http://ns.adobe.com/AdobeInDesign/idml/1.0/packaging" DOMVersion="8.0">
	<FontFamily Self="di3f" Name="Courier (TT)">
		<Font Self="di3fFontnCourier (TT) Regular" FontFamily="Courier (TT)" Name="Courier (TT) Regular" PostScriptName="Courier" Status="NotAvailable" FontStyleName="Regular" FontType="TrueType" WritingScript="0" FullName="Courier" FullNameNative="Courier" FontStyleNameNative="Regular" PlatformName="$ID/" Version="5.1d1e1" />
		<Font Self="di3fFontnCourier (TT) Bold" FontFamily="Courier (TT)" Name="Courier (TT) Bold" PostScriptName="Courier-Bold" Status="Substituted" FontStyleName="Bold" FontType="TrueType" WritingScript="0" FullName="Courier Bold" FullNameNative="Courier Bold" FontStyleNameNative="Bold" PlatformName="$ID/" Version="5.1d1e1" />
		<Font Self="di3fFontnCourier (TT) Oblique" FontFamily="Courier (TT)" Name="Courier (TT) Oblique" PostScriptName="Courier-Oblique" Status="Substituted" FontStyleName="Oblique" FontType="TrueType" WritingScript="0" FullName="Courier Oblique" FullNameNative="Courier Oblique" FontStyleNameNative="Oblique" PlatformName="$ID/" Version="6.0d7e1" />
		<Font Self="di3fFontnCourier (TT) Bold Oblique" FontFamily="Courier (TT)" Name="Courier (TT) Bold Oblique" PostScriptName="Courier-BoldOblique" Status="Substituted" FontStyleName="Bold Oblique" FontType="TrueType" WritingScript="0" FullName="Courier Bold Oblique" FullNameNative="Courier Bold Oblique" FontStyleNameNative="Bold Oblique" PlatformName="$ID/" Version="6.0d7e1" />
	</FontFamily>
	<FontFamily Self="di88" Name="Myriad Pro">
		<Font Self="di88FontnMyriad Pro Light Condensed" FontFamily="Myriad Pro" Name="Myriad Pro Light Condensed" PostScriptName="MyriadPro-LightCond" Status="Substituted" FontStyleName="Light Condensed" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Light Condensed" FullNameNative="Myriad Pro Light Condensed" FontStyleNameNative="Light Condensed" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
		<Font Self="di88FontnMyriad Pro Light Condensed Italic" FontFamily="Myriad Pro" Name="Myriad Pro Light Condensed Italic" PostScriptName="MyriadPro-LightCondIt" Status="Substituted" FontStyleName="Light Condensed Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Light Condensed Italic" FullNameNative="Myriad Pro Light Condensed Italic" FontStyleNameNative="Light Condensed Italic" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
		<Font Self="di88FontnMyriad Pro Condensed" FontFamily="Myriad Pro" Name="Myriad Pro Condensed" PostScriptName="MyriadPro-Cond" Status="Installed" FontStyleName="Condensed" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Condensed" FullNameNative="Myriad Pro Condensed" FontStyleNameNative="Condensed" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Condensed Italic" FontFamily="Myriad Pro" Name="Myriad Pro Condensed Italic" PostScriptName="MyriadPro-CondIt" Status="Installed" FontStyleName="Condensed Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Condensed Italic" FullNameNative="Myriad Pro Condensed Italic" FontStyleNameNative="Condensed Italic" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Semibold Condensed" FontFamily="Myriad Pro" Name="Myriad Pro Semibold Condensed" PostScriptName="MyriadPro-SemiboldCond" Status="Substituted" FontStyleName="Semibold Condensed" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Semibold Condensed" FullNameNative="Myriad Pro Semibold Condensed" FontStyleNameNative="Semibold Condensed" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
		<Font Self="di88FontnMyriad Pro Semibold Condensed Italic" FontFamily="Myriad Pro" Name="Myriad Pro Semibold Condensed Italic" PostScriptName="MyriadPro-SemiboldCondIt" Status="Substituted" FontStyleName="Semibold Condensed Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Semibold Condensed Italic" FullNameNative="Myriad Pro Semibold Condensed Italic" FontStyleNameNative="Semibold Condensed Italic" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
		<Font Self="di88FontnMyriad Pro Bold Condensed" FontFamily="Myriad Pro" Name="Myriad Pro Bold Condensed" PostScriptName="MyriadPro-BoldCond" Status="Installed" FontStyleName="Bold Condensed" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Bold Condensed" FullNameNative="Myriad Pro Bold Condensed" FontStyleNameNative="Bold Condensed" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Bold Condensed Italic" FontFamily="Myriad Pro" Name="Myriad Pro Bold Condensed Italic" PostScriptName="MyriadPro-BoldCondIt" Status="Installed" FontStyleName="Bold Condensed Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Bold Condensed Italic" FullNameNative="Myriad Pro Bold Condensed Italic" FontStyleNameNative="Bold Condensed Italic" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Black Condensed" FontFamily="Myriad Pro" Name="Myriad Pro Black Condensed" PostScriptName="MyriadPro-BlackCond" Status="Substituted" FontStyleName="Black Condensed" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Black Condensed" FullNameNative="Myriad Pro Black Condensed" FontStyleNameNative="Black Condensed" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
		<Font Self="di88FontnMyriad Pro Black Condensed Italic" FontFamily="Myriad Pro" Name="Myriad Pro Black Condensed Italic" PostScriptName="MyriadPro-BlackCondIt" Status="Substituted" FontStyleName="Black Condensed Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Black Condensed Italic" FullNameNative="Myriad Pro Black Condensed Italic" FontStyleNameNative="Black Condensed Italic" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
		<Font Self="di88FontnMyriad Pro Light" FontFamily="Myriad Pro" Name="Myriad Pro Light" PostScriptName="MyriadPro-Light" Status="Substituted" FontStyleName="Light" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Light" FullNameNative="Myriad Pro Light" FontStyleNameNative="Light" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
		<Font Self="di88FontnMyriad Pro Light Italic" FontFamily="Myriad Pro" Name="Myriad Pro Light Italic" PostScriptName="MyriadPro-LightIt" Status="Substituted" FontStyleName="Light Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Light Italic" FullNameNative="Myriad Pro Light Italic" FontStyleNameNative="Light Italic" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
		<Font Self="di88FontnMyriad Pro Regular" FontFamily="Myriad Pro" Name="Myriad Pro Regular" PostScriptName="MyriadPro-Regular" Status="Installed" FontStyleName="Regular" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro" FullNameNative="Myriad Pro" FontStyleNameNative="Regular" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Italic" FontFamily="Myriad Pro" Name="Myriad Pro Italic" PostScriptName="MyriadPro-It" Status="Installed" FontStyleName="Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Italic" FullNameNative="Myriad Pro Italic" FontStyleNameNative="Italic" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Semibold" FontFamily="Myriad Pro" Name="Myriad Pro Semibold" PostScriptName="MyriadPro-Semibold" Status="Installed" FontStyleName="Semibold" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Semibold" FullNameNative="Myriad Pro Semibold" FontStyleNameNative="Semibold" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Semibold Italic" FontFamily="Myriad Pro" Name="Myriad Pro Semibold Italic" PostScriptName="MyriadPro-SemiboldIt" Status="Installed" FontStyleName="Semibold Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Semibold Italic" FullNameNative="Myriad Pro Semibold Italic" FontStyleNameNative="Semibold Italic" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Bold" FontFamily="Myriad Pro" Name="Myriad Pro Bold" PostScriptName="MyriadPro-Bold" Status="Installed" FontStyleName="Bold" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Bold" FullNameNative="Myriad Pro Bold" FontStyleNameNative="Bold" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Bold Italic" FontFamily="Myriad Pro" Name="Myriad Pro Bold Italic" PostScriptName="MyriadPro-BoldIt" Status="Installed" FontStyleName="Bold Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Bold Italic" FullNameNative="Myriad Pro Bold Italic" FontStyleNameNative="Bold Italic" PlatformName="$ID/" Version="Version 2.037;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di88FontnMyriad Pro Black" FontFamily="Myriad Pro" Name="Myriad Pro Black" PostScriptName="MyriadPro-Black" Status="Substituted" FontStyleName="Black" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Black" FullNameNative="Myriad Pro Black" FontStyleNameNative="Black" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
		<Font Self="di88FontnMyriad Pro Black Italic" FontFamily="Myriad Pro" Name="Myriad Pro Black Italic" PostScriptName="MyriadPro-BlackIt" Status="Substituted" FontStyleName="Black Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Myriad Pro Black Italic" FullNameNative="Myriad Pro Black Italic" FontStyleNameNative="Black Italic" PlatformName="$ID/" Version="Version 2.006;PS 002.000;Core 1.0.38;makeotf.lib1.6.6565" />
	</FontFamily>
	<FontFamily Self="di89" Name="Minion Pro">
		<Font Self="di89FontnMinion Pro Bold Cond" FontFamily="Minion Pro" Name="Minion Pro Bold Cond" PostScriptName="MinionPro-BoldCn" Status="Installed" FontStyleName="Bold Cond" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro Bold Cond" FullNameNative="Minion Pro Bold Cond" FontStyleNameNative="Bold Cond" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di89FontnMinion Pro Bold Cond Italic" FontFamily="Minion Pro" Name="Minion Pro Bold Cond Italic" PostScriptName="MinionPro-BoldCnIt" Status="Installed" FontStyleName="Bold Cond Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro Bold Cond Italic" FullNameNative="Minion Pro Bold Cond Italic" FontStyleNameNative="Bold Cond Italic" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di89FontnMinion Pro Regular" FontFamily="Minion Pro" Name="Minion Pro Regular" PostScriptName="MinionPro-Regular" Status="Installed" FontStyleName="Regular" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro" FullNameNative="Minion Pro" FontStyleNameNative="Regular" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di89FontnMinion Pro Italic" FontFamily="Minion Pro" Name="Minion Pro Italic" PostScriptName="MinionPro-It" Status="Installed" FontStyleName="Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro Italic" FullNameNative="Minion Pro Italic" FontStyleNameNative="Italic" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di89FontnMinion Pro Medium" FontFamily="Minion Pro" Name="Minion Pro Medium" PostScriptName="MinionPro-Medium" Status="Installed" FontStyleName="Medium" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro Medium" FullNameNative="Minion Pro Medium" FontStyleNameNative="Medium" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di89FontnMinion Pro Medium Italic" FontFamily="Minion Pro" Name="Minion Pro Medium Italic" PostScriptName="MinionPro-MediumIt" Status="Installed" FontStyleName="Medium Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro Medium Italic" FullNameNative="Minion Pro Medium Italic" FontStyleNameNative="Medium Italic" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di89FontnMinion Pro Semibold" FontFamily="Minion Pro" Name="Minion Pro Semibold" PostScriptName="MinionPro-Semibold" Status="Installed" FontStyleName="Semibold" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro Semibold" FullNameNative="Minion Pro Semibold" FontStyleNameNative="Semibold" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di89FontnMinion Pro Semibold Italic" FontFamily="Minion Pro" Name="Minion Pro Semibold Italic" PostScriptName="MinionPro-SemiboldIt" Status="Installed" FontStyleName="Semibold Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro Semibold Italic" FullNameNative="Minion Pro Semibold Italic" FontStyleNameNative="Semibold Italic" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di89FontnMinion Pro Bold" FontFamily="Minion Pro" Name="Minion Pro Bold" PostScriptName="MinionPro-Bold" Status="Installed" FontStyleName="Bold" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro Bold" FullNameNative="Minion Pro Bold" FontStyleNameNative="Bold" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
		<Font Self="di89FontnMinion Pro Bold Italic" FontFamily="Minion Pro" Name="Minion Pro Bold Italic" PostScriptName="MinionPro-BoldIt" Status="Installed" FontStyleName="Bold Italic" FontType="OpenTypeCFF" WritingScript="0" FullName="Minion Pro Bold Italic" FullNameNative="Minion Pro Bold Italic" FontStyleNameNative="Bold Italic" PlatformName="$ID/" Version="Version 2.030;PS 2.000;hotconv 1.0.51;makeotf.lib2.0.18671" />
	</FontFamily>
	<FontFamily Self="di96" Name="Kozuka Mincho Pro">
		<Font Self="di96FontnKozuka Mincho Pro EL" FontFamily="Kozuka Mincho Pro" Name="Kozuka Mincho Pro EL" PostScriptName="KozMinPro-ExtraLight" Status="Installed" FontStyleName="EL" FontType="OpenTypeCID" WritingScript="1" FullName="Kozuka Mincho Pro EL" FullNameNative="小塚明朝 Pro EL" FontStyleNameNative="EL" PlatformName="$ID/" Version="Version 4.000;PS 4;Core 1.0.38;makeotf.lib1.7.12746" />
		<Font Self="di96FontnKozuka Mincho Pro L" FontFamily="Kozuka Mincho Pro" Name="Kozuka Mincho Pro L" PostScriptName="KozMinPro-Light" Status="Installed" FontStyleName="L" FontType="OpenTypeCID" WritingScript="1" FullName="Kozuka Mincho Pro L" FullNameNative="小塚明朝 Pro L" FontStyleNameNative="L" PlatformName="$ID/" Version="Version 4.000;PS 4;Core 1.0.38;makeotf.lib1.7.12746" />
		<Font Self="di96FontnKozuka Mincho Pro R" FontFamily="Kozuka Mincho Pro" Name="Kozuka Mincho Pro R" PostScriptName="KozMinPro-Regular" Status="Installed" FontStyleName="R" FontType="OpenTypeCID" WritingScript="1" FullName="Kozuka Mincho Pro R" FullNameNative="小塚明朝 Pro R" FontStyleNameNative="R" PlatformName="$ID/" Version="Version 4.001;PS 4.001;Core 1.0.38;makeotf.lib1.7.9028" />
		<Font Self="di96FontnKozuka Mincho Pro M" FontFamily="Kozuka Mincho Pro" Name="Kozuka Mincho Pro M" PostScriptName="KozMinPro-Medium" Status="Installed" FontStyleName="M" FontType="OpenTypeCID" WritingScript="1" FullName="Kozuka Mincho Pro M" FullNameNative="小塚明朝 Pro M" FontStyleNameNative="M" PlatformName="$ID/" Version="Version 4.000;PS 4;Core 1.0.38;makeotf.lib1.7.12746" />
		<Font Self="di96FontnKozuka Mincho Pro B" FontFamily="Kozuka Mincho Pro" Name="Kozuka Mincho Pro B" PostScriptName="KozMinPro-Bold" Status="Installed" FontStyleName="B" FontType="OpenTypeCID" WritingScript="1" FullName="Kozuka Mincho Pro B" FullNameNative="小塚明朝 Pro B" FontStyleNameNative="B" PlatformName="$ID/" Version="Version 4.000;PS 4;Core 1.0.38;makeotf.lib1.7.12746" />
		<Font Self="di96FontnKozuka Mincho Pro H" FontFamily="Kozuka Mincho Pro" Name="Kozuka Mincho Pro H" PostScriptName="KozMinPro-Heavy" Status="Installed" FontStyleName="H" FontType="OpenTypeCID" WritingScript="1" FullName="Kozuka Mincho Pro H" FullNameNative="小塚明朝 Pro H" FontStyleNameNative="H" PlatformName="$ID/" Version="Version 4.000;PS 4;Core 1.0.38;makeotf.lib1.7.12746" />
	</FontFamily>
	<FontFamily Self="di206" Name="Helvetica">
		<Font Self="di206FontnHelvetica Regular" FontFamily="Helvetica" Name="Helvetica Regular" PostScriptName="Helvetica" Status="Substituted" FontStyleName="Regular" FontType="TrueType" WritingScript="0" FullName="Helvetica" FullNameNative="Helvetica" FontStyleNameNative="Regular" PlatformName="$ID/" Version="3.0" />
		<Font Self="di206FontnHelvetica Bold" FontFamily="Helvetica" Name="Helvetica Bold" PostScriptName="Helvetica-Bold" Status="Substituted" FontStyleName="Bold" FontType="TrueType" WritingScript="0" FullName="Helvetica Bold" FullNameNative="Helvetica Bold" FontStyleNameNative="Bold" PlatformName="$ID/" Version="3.0" />
		<Font Self="di206FontnHelvetica Oblique" FontFamily="Helvetica" Name="Helvetica Oblique" PostScriptName="Helvetica-Oblique" Status="Substituted" FontStyleName="Oblique" FontType="TrueType" WritingScript="0" FullName="Helvetica Oblique" FullNameNative="Helvetica Oblique" FontStyleNameNative="$ID/Oblique" PlatformName="$ID/" Version="7.0d20e1" />
		<Font Self="di206FontnHelvetica Bold Oblique" FontFamily="Helvetica" Name="Helvetica Bold Oblique" PostScriptName="Helvetica-BoldOblique" Status="Substituted" FontStyleName="Bold Oblique" FontType="TrueType" WritingScript="0" FullName="Helvetica Bold Oblique" FullNameNative="Helvetica Bold Oblique" FontStyleNameNative="$ID/Bold Oblique" PlatformName="$ID/" Version="7.0d20e1" />
		<Font Self="di206FontnHelvetica Light" FontFamily="Helvetica" Name="Helvetica Light" PostScriptName="Helvetica-Light" Status="Substituted" FontStyleName="Light" FontType="TrueType" WritingScript="0" FullName="Helvetica Light" FullNameNative="Helvetica Light" FontStyleNameNative="Light" PlatformName="$ID/" Version="7.0d20e1" />
		<Font Self="di206FontnHelvetica Light Oblique" FontFamily="Helvetica" Name="Helvetica Light Oblique" PostScriptName="Helvetica-LightOblique" Status="Substituted" FontStyleName="Light Oblique" FontType="TrueType" WritingScript="0" FullName="Helvetica Light Oblique" FullNameNative="Helvetica Light Oblique" FontStyleNameNative="Light Oblique" PlatformName="$ID/" Version="7.0d20e1" />
	</FontFamily>
	<FontFamily Self="di208" Name="JCB Euro">
		<Font Self="di208FontnJCB Euro Light" FontFamily="JCB Euro" Name="JCB Euro Light" PostScriptName="JCBEuroLight" Status="Substituted" FontStyleName="Light" FontType="Type1" WritingScript="0" FullName="JCBEuroLight" FullNameNative="JCBEuroLight" FontStyleNameNative="Light" PlatformName="$ID/" Version="001.000" />
		<Font Self="di208FontnJCB Euro Roman" FontFamily="JCB Euro" Name="JCB Euro Roman" PostScriptName="JCBEuroRoman" Status="Substituted" FontStyleName="Roman" FontType="Type1" WritingScript="0" FullName="JCBEuroRoman" FullNameNative="JCBEuroRoman" FontStyleNameNative="Roman" PlatformName="$ID/" Version="001.000" />
		<Font Self="di208FontnJCB Euro Italic" FontFamily="JCB Euro" Name="JCB Euro Italic" PostScriptName="JCBEuroItalic" Status="Substituted" FontStyleName="Italic" FontType="Type1" WritingScript="0" FullName="JCBEuroItalic" FullNameNative="JCBEuroItalic" FontStyleNameNative="Italic" PlatformName="$ID/" Version="001.000" />
		<Font Self="di208FontnJCB Euro Bold" FontFamily="JCB Euro" Name="JCB Euro Bold" PostScriptName="JCBEuroBold" Status="Substituted" FontStyleName="Bold" FontType="Type1" WritingScript="0" FullName="JCBEuroBold" FullNameNative="JCBEuroBold" FontStyleNameNative="Bold" PlatformName="$ID/" Version="001.000" />
		<Font Self="di208FontnJCB Euro Bold Italic" FontFamily="JCB Euro" Name="JCB Euro Bold Italic" PostScriptName="JCBEuroBoldItalic" Status="Substituted" FontStyleName="Bold Italic" FontType="Type1" WritingScript="0" FullName="JCBEuroBoldItalic" FullNameNative="JCBEuroBoldItalic" FontStyleNameNative="$ID/Bold Italic" PlatformName="$ID/" Version="001.000" />
		<Font Self="di208FontnJCB Euro Extra Bold" FontFamily="JCB Euro" Name="JCB Euro Extra Bold" PostScriptName="JCBEuroExtraBold" Status="Substituted" FontStyleName="Extra Bold" FontType="Type1" WritingScript="0" FullName="JCBEuroExtraBold" FullNameNative="JCBEuroExtraBold" FontStyleNameNative="$ID/Extra Bold" PlatformName="$ID/" Version="001.000" />
		<Font Self="di208FontnJCB Euro Ultra Bold" FontFamily="JCB Euro" Name="JCB Euro Ultra Bold" PostScriptName="JCBEuroUltraBold" Status="Substituted" FontStyleName="Ultra Bold" FontType="Type1" WritingScript="0" FullName="JCBEuroUltraBold" FullNameNative="JCBEuroUltraBold" FontStyleNameNative="$ID/Ultra Bold" PlatformName="$ID/" Version="001.000" />
	</FontFamily>
	<CompositeFont Self="CompositeFont/$ID/[No composite font]" Name="$ID/[No composite font]">
		<CompositeFontEntry Self="u95" Name="$ID/Kanji" FontStyle="$ID/R" RelativeSize="100" HorizontalScale="100" VerticalScale="100" Locked="true" ScaleOption="true" BaselineShift="0">
			<Properties>
				<AppliedFont type="string">Kozuka Mincho Pro</AppliedFont>
			</Properties>
		</CompositeFontEntry>
		<CompositeFontEntry Self="u97" Name="$ID/Kana" FontStyle="$ID/R" RelativeSize="100" HorizontalScale="100" VerticalScale="100" CustomCharacters="ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろゎわゐゑをんゔゕゖゝゞァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロヮワヰヱヲンヴヵヶヷヸヹヺーヽヾ" Locked="true" ScaleOption="true" BaselineShift="0">
			<Properties>
				<AppliedFont type="string">Kozuka Mincho Pro</AppliedFont>
			</Properties>
		</CompositeFontEntry>
		<CompositeFontEntry Self="u98" Name="$ID/Punctuation" FontStyle="$ID/R" RelativeSize="100" HorizontalScale="100" VerticalScale="100" CustomCharacters="—―‖‘’“”‥…′″∥、。〈〉《》「」『』【】〔〕〜・！（），．／：；？［］｛｝～" Locked="true" ScaleOption="true" BaselineShift="0">
			<Properties>
				<AppliedFont type="string">Kozuka Mincho Pro</AppliedFont>
			</Properties>
		</CompositeFontEntry>
		<CompositeFontEntry Self="u99" Name="$ID/Symbols" FontStyle="$ID/R" RelativeSize="100" HorizontalScale="100" VerticalScale="100" CustomCharacters="¢£§¨¬°±´¶×÷ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφχψωЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё‐†‡‰※℃Å←↑→↓⇒⇔∀∂∃∇∈∋−√∝∞∠∧∨∩∪∫∬∴∵∽≒≠≡≦≧≪≫⊂⊃⊆⊇⊥⌒■□▲△▼▽◆◇○◎●◯★☆♀♂♪♭♯〃〆〇〒〓゛゜＃＄％＆＊＋－０１２３４５６７８９＜＝＞＠ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ＼＾＿｀ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ｜￠￡￢￣￥" Locked="true" ScaleOption="true" BaselineShift="0">
			<Properties>
				<AppliedFont type="string">Kozuka Mincho Pro</AppliedFont>
			</Properties>
		</CompositeFontEntry>
		<CompositeFontEntry Self="u9a" Name="$ID/Alphabetic" FontStyle="$ID/Regular" RelativeSize="100" HorizontalScale="100" VerticalScale="100" CustomCharacters=" !&quot;#$%&amp;&apos;()*+,-./:;&lt;=&gt;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_\`abcdefghijklmnopqrstuvwxyz{|}~ ¡¤¥¦©ª«­®¯²³µ·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿıŒœŠšŸŽžƒˆˇ˘˙˚˛˜˝–‚„•‹›⁄€™∆∏∑≈≤≥◊ﬀﬁﬂﬃﬄﬅﬆ" Locked="true" ScaleOption="false" BaselineShift="0">
			<Properties>
				<AppliedFont type="string">Courier (TT)</AppliedFont>
			</Properties>
		</CompositeFontEntry>
		<CompositeFontEntry Self="u9b" Name="$ID/Numbers" FontStyle="$ID/Regular" RelativeSize="100" HorizontalScale="100" VerticalScale="100" CustomCharacters="0123456789" Locked="true" ScaleOption="false" BaselineShift="0">
			<Properties>
				<AppliedFont type="string">Courier (TT)</AppliedFont>
			</Properties>
		</CompositeFontEntry>
	</CompositeFont>
</idPkg:Fonts>`;
